---
apiVersion: v1
data:
  mongo-url: mongo-service
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: myapp-argo-application:/ConfigMap:dev/mongo-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mongo-url":"mongo-service"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"myapp-argo-application:/ConfigMap:dev/mongo-config"},"name":"mongo-config","namespace":"dev"}}
  creationTimestamp: "2025-07-22T17:26:57Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mongo-url: {}
      f:metadata:
        f:annotations:
          .: {}
          f:argocd.argoproj.io/tracking-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: argocd-controller
    operation: Update
    time: "2025-07-22T17:26:57Z"
  name: mongo-config
  namespace: dev
  resourceVersion: "2866"
  uid: b85194c9-5840-4ca8-8bd0-090481fdf0de

---
apiVersion: v1
data:
  mongo-password: ++++++++
  mongo-user: ++++++++
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: myapp-argo-application:/Secret:dev/mongo-secret
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"mongo-password":"++++++++","mongo-user":"++++++++"},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"myapp-argo-application:/Secret:dev/mongo-secret"},"name":"mongo-secret","namespace":"dev"},"type":"opaque"}'
  creationTimestamp: "2025-07-22T17:26:57Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mongo-password: {}
        f:mongo-user: {}
      f:metadata:
        f:annotations:
          .: {}
          f:argocd.argoproj.io/tracking-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:type: {}
    manager: argocd-controller
    operation: Update
    time: "2025-07-22T17:26:57Z"
  name: mongo-secret
  namespace: dev
  resourceVersion: "2865"
  uid: 54236584-c85c-4de5-bafb-e205c3c2aaef
type: opaque

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: myapp-argo-application:/Service:dev/mongo-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"myapp-argo-application:/Service:dev/mongo-service"},"name":"mongo-service","namespace":"dev"},"spec":{"ports":[{"port":27017,"protocol":"TCP","targetPort":27017}],"selector":{"app":"mongo"}}}
  creationTimestamp: "2025-07-22T17:26:57Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:argocd.argoproj.io/tracking-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":27017,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: argocd-controller
    operation: Update
    time: "2025-07-22T17:26:57Z"
  name: mongo-service
  namespace: dev
  resourceVersion: "2871"
  uid: 678758e0-cf5c-4948-980c-f83e892524e5
spec:
  clusterIP: 10.107.234.23
  clusterIPs:
  - 10.107.234.23
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: myapp-argo-application:/Service:dev/webapp-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"myapp-argo-application:/Service:dev/webapp-service"},"name":"webapp-service","namespace":"dev"},"spec":{"ports":[{"nodePort":30100,"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"webapp"},"type":"NodePort"}}
  creationTimestamp: "2025-07-22T17:26:57Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:argocd.argoproj.io/tracking-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":3000,"protocol":"TCP"}:
            .: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: argocd-controller
    operation: Update
    time: "2025-07-22T17:26:57Z"
  name: webapp-service
  namespace: dev
  resourceVersion: "2874"
  uid: df572531-3824-4951-942a-d102533da607
spec:
  clusterIP: 10.101.31.4
  clusterIPs:
  - 10.101.31.4
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30100
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: myapp-argo-application:apps/Deployment:dev/mongo-deployment
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"myapp-argo-application:apps/Deployment:dev/mongo-deployment"},"labels":{"app":"mongo"},"name":"mongo-deployment","namespace":"dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mongo"}},"template":{"metadata":{"labels":{"app":"mongo"}},"spec":{"containers":[{"env":[{"name":"MONGO_INITDB_ROOT_USERNAME","valueFrom":{"secretKeyRef":{"key":"mongo-user","name":"mongo-secret"}}},{"name":"MONGO_INITDB_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mongo-password","name":"mongo-secret"}}}],"image":"mongo:5.0","name":"mongodb","ports":[{"containerPort":27017}]}]}}}}
  creationTimestamp: "2025-07-22T17:26:58Z"
  generation: 1
  labels:
    app: mongo
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:argocd.argoproj.io/tracking-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"mongodb"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"MONGO_INITDB_ROOT_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef: {}
                  k:{"name":"MONGO_INITDB_ROOT_USERNAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":27017,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: argocd-controller
    operation: Update
    time: "2025-07-22T17:26:58Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2025-07-22T18:05:09Z"
  name: mongo-deployment
  namespace: dev
  resourceVersion: "4794"
  uid: 89c4256f-2617-459b-b24c-4b2c7bf5169b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-user
              name: mongo-secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-password
              name: mongo-secret
        image: mongo:5.0
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-22T18:05:09Z"
    lastUpdateTime: "2025-07-22T18:05:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-22T18:05:09Z"
    lastUpdateTime: "2025-07-22T18:05:09Z"
    message: ReplicaSet "mongo-deployment-7cccf8b6d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: myapp-argo-application:apps/Deployment:dev/webapp-deployment
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"myapp-argo-application:apps/Deployment:dev/webapp-deployment"},"labels":{"app":"webapp"},"name":"webapp-deployment","namespace":"dev"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"webapp"}},"template":{"metadata":{"labels":{"app":"webapp"}},"spec":{"containers":[{"env":[{"name":"USER_NAME","valueFrom":{"secretKeyRef":{"key":"mongo-user","name":"mongo-secret"}}},{"name":"USER_PWD","valueFrom":{"secretKeyRef":{"key":"mongo-password","name":"mongo-secret"}}},{"name":"DB_URL","valueFrom":{"configMapKeyRef":{"key":"mongo-url","name":"mongo-config"}}}],"image":"nanajanashia/k8s-demo-app:v1.0","name":"webapp","ports":[{"containerPort":3000}]}]}}}}
  creationTimestamp: "2025-07-22T17:26:58Z"
  generation: 3
  labels:
    app: webapp
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:argocd.argoproj.io/tracking-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"webapp"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"DB_URL"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"USER_NAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef: {}
                  k:{"name":"USER_PWD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":3000,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: argocd-controller
    operation: Update
    time: "2025-07-22T18:30:10Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2025-07-22T18:30:16Z"
  name: webapp-deployment
  namespace: dev
  resourceVersion: "6316"
  uid: 23a1574b-abc5-4fa7-a081-df5955a7059e
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              key: mongo-user
              name: mongo-secret
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              key: mongo-password
              name: mongo-secret
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              key: mongo-url
              name: mongo-config
        image: nanajanashia/k8s-demo-app:v1.0
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-07-22T18:05:13Z"
    lastUpdateTime: "2025-07-22T18:05:16Z"
    message: ReplicaSet "webapp-deployment-6bb4795f54" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-22T18:30:16Z"
    lastUpdateTime: "2025-07-22T18:30:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
